import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react";

const config = defineConfig({
    globalCss: {
        ":root": {
            "--color-bg-app": "#090d12",
            "--color-bg-panel": "#0c1117",
            "--color-bg-card": "#111720",
            "--color-bg-muted": "#0f141b",
            "--color-bg-soft": "#151c26",
            "--color-bg-hover": "#161e2a",
            "--color-bg-hover-strong": "#111e34",
            "--color-bg-overlay": "rgba(4, 7, 12, 0.82)",
            "--color-text-primary": "#f5f7fb",
            "--color-text-secondary": "#b0bccf",
            "--color-text-muted": "#90a0b7",
            "--color-text-subtle": "#728198",
            "--color-text-strong": "#d8e1ee",
            "--color-text-inverse": "#f8fbff",
            "--color-border-default": "#273140",
            "--color-border-strong": "#2b3544",
            "--color-border-soft": "#344053",
            "--color-accent": "#2d6cdf",
            "--color-accent-hover": "#245ab8",
            "--color-accent-border": "#4b7ee8",
            "--color-accent-surface": "#13223a",
            "--color-accent-surface-strong": "#15233b",
            "--color-success-bg": "#0f211d",
            "--color-success-border": "#2f6c58",
            "--color-success-text": "#b7f5de",
            "--color-danger-bg": "#2a1317",
            "--color-danger-bg-soft": "#34161b",
            "--color-danger-border": "#8c3a46",
            "--color-danger-text": "#ffc6ce",
            "--color-danger-heading": "#ffe1e6",
            "--color-link": "#8db4ff",
            "--color-scroll-thumb": "#3b4657",
            "--color-scroll-track": "#0f141b",
        },
        "html[data-theme='light']": {
            "--color-bg-app": "#f4f7fb",
            "--color-bg-panel": "#eef2f8",
            "--color-bg-card": "#ffffff",
            "--color-bg-muted": "#f7f9fc",
            "--color-bg-soft": "#edf2f8",
            "--color-bg-hover": "#e6edf7",
            "--color-bg-hover-strong": "#e7f0ff",
            "--color-bg-overlay": "rgba(15, 23, 42, 0.22)",
            "--color-text-primary": "#152033",
            "--color-text-secondary": "#4c5b70",
            "--color-text-muted": "#68788e",
            "--color-text-subtle": "#8391a4",
            "--color-text-strong": "#2b3950",
            "--color-text-inverse": "#f8fbff",
            "--color-border-default": "#d5dde8",
            "--color-border-strong": "#c7d0dc",
            "--color-border-soft": "#d1dae6",
            "--color-accent": "#2d6cdf",
            "--color-accent-hover": "#245ab8",
            "--color-accent-border": "#3d6ed1",
            "--color-accent-surface": "#dde9ff",
            "--color-accent-surface-strong": "#d5e4ff",
            "--color-success-bg": "#e7f6ef",
            "--color-success-border": "#6cb18e",
            "--color-success-text": "#1d5d3d",
            "--color-danger-bg": "#fcebed",
            "--color-danger-bg-soft": "#fff0f2",
            "--color-danger-border": "#d48695",
            "--color-danger-text": "#9a324a",
            "--color-danger-heading": "#8a2941",
            "--color-link": "#245ab8",
            "--color-scroll-thumb": "#b0bccf",
            "--color-scroll-track": "#eef2f8",
        },
        "html, body": {
            background: "var(--color-bg-app)",
            color: "var(--color-text-primary)",
        },
        body: {
            minHeight: "100vh",
            transitionProperty: "background-color, color",
            transitionDuration: "180ms",
            transitionTimingFunction: "ease",
        },
        "#root": {
            minHeight: "100vh",
        },
        "*": {
            scrollbarColor: "var(--color-scroll-thumb) var(--color-scroll-track)",
        },
        "::selection": {
            background: "var(--color-accent)",
            color: "var(--color-text-inverse)",
        },
        "button, a, input, textarea, select": {
            transitionProperty: "background-color, border-color, color, box-shadow, transform",
            transitionDuration: "160ms",
            transitionTimingFunction: "ease",
        },
        "button:not(:disabled), a, [role='button']": {
            cursor: "pointer",
        },
        "button:not(:disabled):hover, a:hover, [role='button']:hover": {
            transform: "translateY(-1px)",
        },
        "button:focus-visible, a:focus-visible, input:focus-visible, textarea:focus-visible, select:focus-visible": {
            outline: "none",
            boxShadow: "0 0 0 1px var(--color-accent-border)",
        },
        "input:hover, textarea:hover, select:hover": {
            borderColor: "var(--color-accent-border)",
        },
    },
    theme: {
        tokens: {
            fonts: {
                heading: { value: '"Segoe UI", "Aptos", sans-serif' },
                body: { value: '"Segoe UI", "Aptos", sans-serif' },
            },
        },
    },
});

export const appSystem = createSystem(defaultConfig, config);
